export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_POSTS      = 'GET_POSTS';
export const GET_POST       = 'GET_POST';
export const POST_ADD       = 'POST_ADD';
export const POST_ADDED     = 'POST_ADDED';
export const UPDATE_POST    = 'UPDATE_POST';
export const DELETE_POST    = 'DELETE_POST';
export const UPVOTE_POST    = 'UPVOTE_POST';
export const DOWNVOTE_POST  = 'DOWNVOTE_POST';

export const SORT_POSTS_BY_CREATION_TIME_ASC  = 'SORT_POSTS_BY_CREATION_TIME_ASC';
export const SORT_POSTS_BY_CREATION_TIME_DESC = 'SORT_POSTS_BY_CREATION_TIME_DESC';
export const SORT_POSTS_BY_VOTES_ASC          = 'SORT_POSTS_BY_VOTES_ASC';
export const SORT_POSTS_BY_VOTES_DESC         = 'SORT_POSTS_BY_VOTES_DESC';

export const COMMENT_ADD        = 'COMMENT_ADD';
export const GET_POST_COMMENTS  = 'GET_POST_COMMENTS';
export const DELETE_COMMENT     = 'DELETE_COMMENT';
export const EDIT_COMMENT       = 'EDIT_COMMENT';
export const UPVOTE_COMMENT     = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT   = 'DOWNVOTE_COMMENT';

export const SORT_COMMENTS_BY_CREATION_TIME_ASC  = 'SORT_COMMENTS_BY_CREATION_TIME_ASC';
export const SORT_COMMENTS_BY_CREATION_TIME_DESC = 'SORT_COMMENTS_BY_CREATION_TIME_DESC';
export const SORT_COMMENTS_BY_VOTES_ASC          = 'SORT_COMMENTS_BY_VOTES_ASC';
export const SORT_COMMENTS_BY_VOTES_DESC         = 'SORT_COMMENTS_BY_VOTES_DESC';